/*DOMAINS*/
CREATE DOMAIN T_ID AS SERIAL PRIMARY KEY;
CREATE DOMAIN T_NAME AS VARCHAR(100);
CREATE DOMAIN T_EMAIL AS TEXT UNIQUE NOT NULL;
CREATE DOMAIN T_COINS AS BIGINT DEFAULT 0;
CREATE DOMAIN T_JOINED AS TIMESTAMP NOT NULL;
CREATE DOMAIN T_HASH AS VARCHAR(1OO) NOT NULL;

/*USERS TABLE*/
CREATE TABLE USERS (
    ID T_ID,
    NAME T_NAME,
    EMAIL T_EMAIL,
    COINS T_COINS,
    JOINED T_JOINED
);

CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL TEXT UNIQUE NOT NULL,
    COINS BIGINT DEFAULT 0,
    JOINED TIMESTAMP NOT NULL
);


/*LOGIN TABLE*/

CREATE TABLE LOGIN (
    ID T_ID, 
    HASH T_HASH, 
    EMAIL T_EMAIL
);

CREATE TABLE LOGIN (
    ID SERIAL PRIMARY KEY, 
    HASH VARCHAR(1OO) NOT NULL, 
    EMAIL TEXT UNIQUE NOT NULL
);